# Generated by Django 5.2.6 on 2025-09-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                ("factory_id", models.AutoField(primary_key=True, serialize=False)),
                ("factory_name", models.CharField(max_length=40, unique=True)),
                ("factory_location", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyEntry",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "energy_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("diesel", "Diesel"),
                            ("firewood", "Firewood"),
                        ],
                        max_length=100,
                    ),
                ),
                ("energy_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "co2_equivalent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tea_processed_amount",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.factory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mcu_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="active", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "factory",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcu",
                        to="factory.factory",
                    ),
                ),
            ],
        ),
    ]
