# Generated by Django 5.2.6 on 2025-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyentry',
            name='co2_equivalent',
            field=models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='energyentry',
            name='energy_amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
