# Generated by Django 4.2.24 on 2025-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0002_alter_energyentry_co2_equivalent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyentry",
            name="co2_equivalent",
            field=models.DecimalField(
                blank=True, decimal_places=6, editable=False, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="energyentry",
            name="energy_amount",
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name="energyentry",
            name="tea_processed_amount",
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
    ]
