# Generated by Django 4.2.24 on 2025-09-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emissions",
            fields=[
                ("emissions_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "emission_rate",
                    models.DecimalField(decimal_places=15, max_digits=15),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mcu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissions",
                        to="factory.mcu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compliance",
            fields=[
                ("compliance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "compliance_target",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        default="compliant", editable=False, max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factory.factory",
                    ),
                ),
            ],
        ),
    ]
