# Generated by Django 5.2.6 on 2025-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='emission_rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
