# Generated by Django 4.2.24 on 2025-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissions",
            name="emission_rate",
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
