name: ci-cd

on: 
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache Poetry installation
      uses: actions/cache@v3
      with:
        path: ~/.local/share/pypoetry
        key: poetry-2.1.4
        restore-keys: |
          poetry-

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.4
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: poetry-deps-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-deps-

    - name: Install packages
      run: poetry install --no-interaction

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=pycounts --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml

    - name: Build documentation
      run: poetry run make html --directory docs/
