name: ci-cd

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8.10'
    - name: Install Poetry
      run: pip install poetry==1.8.3
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: sqlite:///:memory
      run: poetry run python manage.py test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8.10'
    - name: Install Poetry
      run: pip install poetry==1.8.3
    - name: Install dependencies
      run: poetry install --no-root
    - name: Build static files
      run: poetry run python manage.py collectstatic --noinput
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      run: |
        npm install -g vercel
        vercel --prod --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --scope $VERCEL_ORG_ID
