name: Automated API tests using Postman CLI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    env:
      COL_UID: [ ca14796e-3a0f-4fc2-8ec3-4f008bc17536]
      ENV_UID: [ aaf667a5-9fae-4cc6-937d-e92eb470f211]
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key "$POSTMAN_API_KEY"
      - name: Run API tests
        run: |
          mkdir -p reports
          postman collection run "$COL_UID" -e "$ENV_UID" \
            --reporters cli,junit \
            --reporter-junit-export reports/junit.xml
      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: postman-junit
          path: reports/junit.xml